project: morphoaware
run_name: debuggingMetamorph
tags: []
seed: -1
wandb_dir: null
wandb_mode: "online" # disabled | online | offline

SLURM_JOB_ID: ${oc.env:SLURM_JOB_ID,null}
SLURM_ARRAY_JOB_ID: ${oc.env:SLURM_ARRAY_JOB_ID,null}
SLURM_ARRAY_TASK_ID: ${oc.env:SLURM_ARRAY_TASK_ID,null}
HYDRA_SWEEP_DIR: ${oc.env:HYDRA_SWEEP_DIR,null}

signal_handling: "standard" # standard | requeue