
defaults:
  - meta: meta
  - dataset: unimals_train
  - eval: paths
  - model: modumorph
  - script: train
  - task: ft_rot
  - vma: vma_only
  - secrets: secrets

other_yacs_args: ""# DEVICE cpu"
postrun_eval_dir: "./savedruns" # only used by postrun_eval, ignore otherwise
postrun_eval_del_previous_evals: False