
defaults:
  - meta: meta
  - dataset: unimals_train
  - eval: paths
  - model: metamorph
  - script: train
  - task: ft
  - vma: gt

other_yacs_args: ""# DEVICE cpu"
postrun_eval_dir: "/home/charlie/Desktop/ModuMorph/savedruns" # only used by postrun_eval, ignore otherwise