CFG_DEST: config.yaml
CHECKPOINT_PERIOD: 100
CUDNN:
  BENCHMARK: false
  DETERMINISTIC: true
DESC: ''
DETERMINISTIC: false
DEVICE: cuda:0
ENV:
  ANGLE_RANGE:
  - -0.2
  - 0.2
  AVOID_REWARD_WEIGHT: 100.0
  CTRL_COST_WEIGHT: 0.0
  FIX_ENV: false
  FORWARD_REWARD_WEIGHT: 1.0
  HEALTHY_REWARD: 0.0
  KEYS_TO_KEEP: []
  MODULES:
  - Agent
  - Floor
  NEW_SIM_ON_RESET: true
  RESET_NOISE_SCALE: 0.005
  SKIP_SELF_POS: false
  STAND_HEIGHT_RATIO: 0.5
  STAND_REWARD_WEIGHT: 0.0
  STATE_RANGE:
  - -100.0
  - 100.0
  TASK: locomotion
  TASK_SAMPLING: balanced_replay_buffer
  WALKERS:
  - floor-1409-11-11-01-08-26-42
  - vt-1409-3-14-02-15-26-41
  - vt-5506-7-17-02-15-44-51
  - vt-5506-0-16-02-19-41-18
  - mvt-5506-2-5-17-09-53-52
  - floor-5506-10-1-01-12-44-00
  - floor-1409-10-0-01-11-09-15
  - mvt-5506-15-3-17-08-19-25
  - vt-5506-8-0-02-20-33-52
  - vt-1409-5-9-02-21-58-06
  - floor-1409-8-2-01-16-01-05
  - vt-5506-9-14-02-16-04-50
  - floor-5506-3-10-01-14-19-06
  - floor-1409-1-6-01-07-43-16
  - floor-5506-10-9-01-16-04-28
  - vt-1409-10-1-02-22-33-21
  - floor-1409-5-4-01-13-42-51
  - floor-1409-11-5-01-14-47-29
  - vt-5506-13-0-02-17-53-04
  - vt-1409-13-5-02-18-04-00
  - floor-1409-5-6-01-11-46-39
  - mvt-5506-7-6-17-12-20-01
  - mvt-5506-10-14-17-10-38-34
  - floor-5506-9-15-01-16-19-27
  - vt-5506-5-8-02-16-00-28
  - vt-5506-9-3-02-15-19-17
  - floor-1409-7-6-01-12-11-58
  - floor-1409-9-6-01-13-54-23
  - vt-1409-9-17-02-20-16-00
  - floor-5506-4-14-01-14-32-47
  - floor-1409-15-4-01-15-28-42
  - vt-5506-3-17-02-18-33-45
  - vt-5506-13-10-02-20-49-04
  - mvt-5506-14-4-17-08-14-37
  - vt-1409-2-1-02-19-18-03
  - vt-1409-5-10-02-21-38-25
  - vt-1409-0-15-02-22-16-32
  - floor-1409-9-9-01-14-34-07
  - vt-1409-9-14-02-22-02-11
  - floor-1409-0-3-01-15-56-55
  - mvt-5506-15-6-17-03-13-08
  - mvt-5506-2-16-17-07-02-57
  - mvt-5506-1-12-17-11-10-12
  - floor-1409-8-2-01-10-01-16
  - floor-5506-12-12-01-11-30-00
  - vt-1409-15-5-02-21-44-24
  - mvt-5506-11-13-17-10-06-36
  - floor-5506-2-16-01-10-58-23
  - floor-1409-11-9-01-10-00-52
  - vt-1409-8-6-02-19-32-04
  - vt-1409-12-10-02-21-04-52
  - floor-1409-0-7-01-15-15-26
  - vt-5506-0-12-02-19-26-55
  - vt-5506-14-2-02-15-14-46
  - mvt-5506-3-15-17-12-18-03
  - floor-1409-11-14-01-13-30-11
  - floor-1409-3-5-01-12-07-43
  - vt-5506-8-7-02-22-09-35
  - floor-1409-1-4-01-09-49-50
  - vt-1409-8-12-02-19-46-23
  - vt-5506-3-17-02-17-31-10
  - floor-1409-11-14-01-15-44-14
  - vt-5506-10-12-02-12-35-19
  - mvt-5506-10-16-17-09-26-11
  - floor-5506-14-13-01-15-43-28
  - floor-1409-8-8-01-14-47-11
  - floor-1409-6-12-01-13-27-36
  - floor-5506-11-8-01-12-33-50
  - floor-5506-8-16-01-13-07-43
  - vt-5506-13-4-02-21-40-07
  - mvt-5506-13-10-17-12-25-45
  - mvt-5506-2-17-17-10-16-02
  - vt-1409-6-3-02-22-09-55
  - vt-5506-15-9-02-19-03-39
  - mvt-5506-12-11-17-05-56-16
  - mvt-5506-12-4-17-12-01-27
  - vt-5506-15-16-02-22-21-06
  - mvt-5506-0-12-17-12-16-55
  - floor-1409-7-12-01-11-13-06
  - vt-1409-9-17-02-21-12-51
  - vt-1409-14-9-02-19-21-40
  - floor-5506-12-12-01-15-33-01
  - mvt-5506-4-14-17-10-06-59
  - mvt-5506-12-6-17-12-20-06
  - floor-1409-3-17-01-11-13-22
  - floor-5506-12-14-01-15-22-01
  - mvt-5506-15-15-17-10-52-43
  - vt-5506-13-5-02-21-35-41
  - vt-5506-7-1-02-20-26-46
  - floor-1409-0-12-01-12-30-07
  - floor-5506-9-12-01-10-32-52
  - floor-5506-9-7-01-13-40-02
  - floor-5506-10-6-01-15-48-35
  - vt-1409-0-13-02-20-49-20
  - floor-1409-11-8-01-08-25-42
  - mvt-5506-14-2-17-07-59-45
  - floor-1409-10-3-01-15-34-29
  - mvt-5506-4-9-17-09-31-55
  - vt-5506-10-5-02-14-20-08
  - mvt-5506-1-13-17-12-03-16
  WALKER_DIR: ./unimals_100/train
  WRAPPERS: []
  Z_RANGE:
  - -0.1
  - .inf
ENV_NAME: Unimal-v0
EVAL_PERIOD: -1
EXIT_ON_MJ_STEP_EXCEPTION: false
HFIELD:
  ADAPTIVE_OBS: false
  ADAPTIVE_OBS_SIZE:
  - 0.1
  - 0.5
  - 1.5
  - 5.0
  DIM: 2
  GAP_DEPTH: -10
  NUM_DIVS: 10
  OBS_SIZE:
  - 1
  - 4
  - 4
  - 4
  PADDING: 10
  VIZ: false
LOG_DEST: stdout
LOG_PERIOD: 10
MIRROR_DATA_AUG: false
MODEL:
  ACTION_STD: 0.9
  ACTION_STD_FIXED: true
  ACTOR_CRITIC: ActorCritic
  BASE_CONTEXT_NORM: running
  CONTEXT_OBS_TYPES:
  - body_pos
  - body_ipos
  - body_iquat
  - geom_quat
  - body_mass
  - body_shape
  - jnt_pos
  - joint_range
  - joint_axis
  - gear
  FINETUNE:
    FULL_MODEL: false
    LAYER_SUBSTRING: []
  JOINT_EMBED_SIZE: 128
  LIMB_EMBED_SIZE: 128
  MAX_JOINTS: 16
  MAX_LIMBS: 12
  MLP:
    HIDDEN_DIM: 256
    LAYER_NUM: 3
  OBS_TO_NORM:
  - proprioceptive
  OBS_TYPES:
  - proprioceptive
  - edges
  - obs_padding_mask
  - act_padding_mask
  - context
  - traversals
  - SWAT_RE
  PROPRIOCEPTIVE_OBS_TYPES:
  - body_xpos
  - body_xvelp
  - body_xvelr
  - body_xquat
  - body_pos
  - body_ipos
  - body_iquat
  - geom_quat
  - body_mass
  - body_shape
  - qpos
  - qvel
  - jnt_pos
  - joint_range
  - joint_axis
  - gear
  TRANSFORMER:
    CONSISTENT_DROPOUT: false
    CONTEXT_EMBED_SIZE: 128
    CONTEXT_ENCODER: linear
    CONTEXT_LAYER: 3
    DECODER_DIMS: []
    DECODER_INIT: 0.01
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.0
    EMBEDDING_DROPOUT: true
    EMBEDDING_SCALE: true
    EMBED_INIT: 0.1
    EXT_HIDDEN_DIMS: []
    EXT_MIX: none
    FIX_ATTENTION: false
    HFIELD_IN_FIX_ATTENTION: false
    HN_CONTEXT_ENCODER: linear
    HN_CONTEXT_LAYER_NUM: 1
    HN_DECODER: true
    HN_EMBED: true
    HN_EMBED_INIT: 0.1
    HYPERNET: false
    LINEAR_CONTEXT_LAYER: 2
    NHEAD: 2
    NLAYERS: 5
    PER_NODE_DECODER: false
    PER_NODE_EMBED: false
    POS_EMBEDDING: learnt
    TRAVERSALS:
    - pre
    - inlcrs
    - postlcrs
    USE_MORPHOLOGY_INFO_IN_ATTENTION: false
    USE_SWAT_PE: false
    USE_SWAT_RE: false
  TYPE: transformer
  WRAPPERS:
  - MultiUnimalNodeCentricObservation
  - MultiUnimalNodeCentricAction
NODE_ID: -1
NUM_NODES: 1
OBJECT:
  BALL_RADIUS: 0.15
  BOX_MASS: 1.0
  BOX_POS: []
  BOX_SIDE: 0.5
  CLOSE_PLACEMENT_DIST: 10
  FORWARD_PLACEMENT_DIST:
  - 10
  - 15
  GOAL_POS: []
  NUM_OBSTACLES: 50
  OBSTACLE_LEN_RANGE:
  - 0.5
  - 1
  - 0.1
  OBSTACLE_WIDTH_RANGE:
  - 0.5
  - 1
  - 0.1
  PLACEMENT_BUFFER_LEN: 3
  PLACEMENT_BUFFER_WIDTH: 0
  SUCCESS_MARGIN: 0.5
  TYPE: box
OUT_DIR: /home/charlie/Desktop/ModuMorph/wandb/run-20250508_153750-fshlxgpf/files
PPO:
  BASE_LR: 0.0003
  BATCH_SIZE: 5120
  CHECKPOINT_PATH: ''
  CLIP_EPS: 0.2
  EARLY_EXIT: false
  EARLY_EXIT_MAX_ITERS: 1220
  EARLY_EXIT_STATE_ACTION_PAIRS: 100000000.0
  ENTROPY_COEF: 0.0
  EPOCHS: 8
  EPS: 1.0e-05
  GAE_LAMBDA: 0.95
  GAMMA: 0.99
  KL_TARGET_COEF: 20.0
  LR_POLICY: cos
  MAX_GRAD_NORM: 0.5
  MAX_ITERS: 1220
  MAX_STATE_ACTION_PAIRS: 100000000.0
  MIN_LR: 0.0
  NUM_ENVS: 32
  TIMESTEPS: 2560
  USE_CLIP_VALUE_FUNC: true
  VALUE_COEF: 0.5
  VIDEO_LENGTH: 1000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 5
  WEIGHT_DECAY: 0.0
RNG_SEED: 3525
SAVE_HIST_WEIGHTS: false
TASK_SAMPLING:
  AVG_TYPE: ema
  EMA_ALPHA: 0.1
  PROB_ALPHA: 1.0
TERMINATE_ON_FALL: true
TERRAIN:
  BOUNDARY_WALLS: true
  BOWL_MAX_Z: 1.3
  CENTER_FLAT: 2
  CURVE_HEIGHT_RANGE:
  - 0.6
  - 1.2
  - 0.1
  FLAT_LENGTH_RANGE:
  - 9
  - 15
  - 2
  FLOOR_OFFSET: 0.2
  HFIELD_LENGTH_RANGE:
  - 4
  - 8
  - 4
  INCLINE_ANGLE: 0
  NUM_STEPS: 8
  RUGGED_SQUARE_CLIP_RANGE:
  - 0.2
  - 0.3
  - 0.1
  SIZE:
  - 100
  - 100
  - 1
  START_FLAT: 2
  STEP_HEIGHT: 0.2
  STEP_LENGTH_RANGE:
  - 12
  - 16
  - 4
  TYPES:
  - gap
  - jump
  WALL_LENGTH: 0.1
UNIMAL_TEMPLATE: ./metamorph/envs/assets/unimal.xml
VECENV:
  IN_SERIES: 2
  TYPE: SubprocVecEnv
VIDEO:
  FPS: 30
  HEIGHT: 360
  SAVE: false
  WIDTH: 640
XML:
  FILTER_PARENT: enable
  GEOM_CONDIM: 3
  GEOM_FRICTION:
  - 0.7
  - 0.1
  - 0.1
  NCONMAX: 200
  NJMAX: 1000
  SHADOWCLIP: 0.5
